apply plugin : 'java'
apply plugin : 'eclipse'
repositories {
    maven {    url "http://nufl2vpnexus02.nonprod.nb01.local:8081/repository/central/"
        allowInsecureProtocol = true
    }
}
   dependencies{
       implementation rootProject
 }
  task execPaypageRegistrationIdToTokenExample (type:JavaExec){
	check.dependsOn it
        main='io.github.vantiv.sdk.samples.PaypageRegistrationIdToTokenExample'
        classpath = sourceSets.main.runtimeClasspath	   
}

   
   
  
   
   


